repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.7
    hooks:
      - id: djlint-django
        args:
          [
            "--lint",
            "--reformat",
            "--quiet",
          ]
