# Generated by Django 3.2.16 on 2022-12-05 13:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leeway", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="leewaysimulation",
            name="simulation_started",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="leewaysimulation",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
