# Generated by Django 3.2.16 on 2022-12-05 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leeway", "0002_auto_20221205_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="leewaysimulation",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        )
    ]
