# Generated by Django 3.2.16 on 2022-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leeway", "0003_leewaysimulation_user")]

    operations = [
        migrations.AddField(
            model_name="leewaysimulation",
            name="simulation_finished",
            field=models.DateTimeField(null=True),
        )
    ]
