# Generated by Django 3.2.16 on 2022-12-05 14:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leeway", "0004_leewaysimulation_simulation_finished")]

    operations = [
        migrations.AddField(
            model_name="leewaysimulation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        )
    ]
