# Generated by Django 5.2.7 on 2026-02-20 17:35

from django.db import migrations, models

import opendrift_leeway_webgui.leeway.models


class Migration(migrations.Migration):

    dependencies = [("leeway", "0008_leewaysimulation_traceback")]

    operations = [
        migrations.AddField(
            model_name="leewaysimulation",
            name="geojson",
            field=models.FileField(
                null=True,
                storage=opendrift_leeway_webgui.leeway.models.simulation_storage,
                upload_to="",
                verbose_name="GeoJSON of simulated trajectories",
            ),
        )
    ]
