# Generated by Django 5.2.7 on 2026-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leeway", "0009_leewaysimulation_geojson")]

    operations = [
        migrations.AddField(
            model_name="leewaysimulation",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        )
    ]
