# Generated by Django 6.0.4 on 2026-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leeway", "0012_webhook"),
    ]

    operations = [
        migrations.CreateModel(
            name="IconFiles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("frt", models.CharField(max_length=2, verbose_name="Forecast time")),
                ("file_name", models.CharField(max_length=127, verbose_name="File name of downloaded file")),
                ("download_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
