name: Linting
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format check
        run: ruff format --check .
  djlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install djlint
        run: pip install djlint
      - name: Run djlint
        run: djlint --check --lint opendrift_leeway_webgui
